version: '3.8'

services:

  discord:
    image: discord
    container_name: discord_app
    build:
      context: .
      target: development
    volumes:
      - .:/discord
      - postgres_vol:/vol/postgres
    command: >
      sh -c "python discord_bot.py"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: discord_db
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    expose:
      - ${DB_PORT}
    restart: always
    volumes:
      - .:/discord
      - postgres_vol:/var/lib/postgresql/data

  pgadmin_discord:
    container_name: discord_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  postgres_vol:
