name: CI

on:

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv install -d

      - name: tests
        run:  pipenv run pytest
#
#      - name: install docker-compose
#        run: |
#          pip install docker-compose
#      - name: Run docker-compose
#        run: |
#          docker-compose -f docker-compose.yaml run discord sh -c "pytest"